#!/usr/bin/python -O
# -*- coding: utf-8 -*-

from flask import Flask, request, url_for, render_template
from model import Repository
from model import stock


app = Flask(__name__)


def f_fund(fund, digits=2):
    """ decrate the fund, if positive, use green; negative, use red
    """
    if fund is None:
        return ""

    if fund > 0:
        return "<font color=green>{0:,.{1}f}</font>".format(fund, digits)
    elif fund < 0:
        return "<font color=red>{0:,.{1}f}</font>".format(fund, digits)
    else:
        return "{0:,.{1}f}".format(fund, digits)


@app.route("/")
def index():
    return render_template("hello.html", name="world")


@app.route("/stock_fund")
def stock_fund():
    limit = request.args.get('limit', '30')
    repository = Repository()

    funds = {}
    for code, name in repository.get_codes():
        funds[code + " " + name] = repository.get_stockdata(code, limit)

    tbody = []
    for code, name in repository.get_codes():
        # table header
        tbody.append("""<tr>
    <th nowrap><a href="{url}">{code}</a> {name}</th>
    <th nowrap>日期</th>
    <th nowrap>流入（万）</th>
    <th nowrap>流出（万）</th>
    <th nowrap>净流入（万）</th>
    <th nowrap>净流入/流通 %</th>
    <th nowrap>净流入/当日 %</th>
    <th nowrap>涨跌 %</th>
</tr>""".format(code=code, url=stock.get_url(code), name=name))

        total_funds = 0
        total_percent = 0
        total_increase = 0

        rows = repository.get_stockdata(code, limit)

        first_row = True
        for row in rows:
            tbody.append("""<tr>
    {rowheader}
    <td>{date}</td>
    <td align="right">{fund_in:,.0f}</td>
    <td align="right">{fund_out:,.0f}</td>
    <td align="right">{fund_net}</td>
    <td align="right" nowrap><b>{percent}</b> %</td>
    <td align="right" nowrap><b>{fund_per}</b> %</td>
    <td align="right"><b>{inc_p}</b> %</td>
</tr>""".format(rowheader="<td rowspan={0}>&nbsp;</td>".format(len(rows)) if first_row else "",
                date=row.date,
                fund_in=row.fund_in,
                fund_out=row.fund_out,
                fund_net=f_fund(row.fund_net, 0),
                percent=f_fund(row.percent, 3),
                fund_per=f_fund(row.fund_per),
                inc_p=f_fund(row.inc_p),
                ))
            total_funds += row.fund_net
            total_percent += row.percent
            total_increase += row.inc_p

            first_row = False

        # table footer
        tbody.append("""<tr>
    <td></td>
    <td align="center">合计</td>
    <td></td>
    <td></td>
    <td align="right">{0}</td>
    <td align="right"><b>{1}</b> %</td>
    <td></td>
    <td align="right"><b>{2}</b> %</td>
</tr>""".format(f_fund(total_funds, 0),
                f_fund(total_percent, 3),
                f_fund(total_increase), ))

    html = """<html>
    <head>
        <title>Stock Funds</title>
        <link rel="stylesheet" href="{stylesheet}"/>
    </head>
<body>
<table border=0 cellspacing="1" cellpadding="5">
<col width="70">
<col width="100">
<col width="70">
<col width="80">
<col width="80">
<col width="70">
<col width="80">
<col width="90">
{tbody}
</table>
</body>
</html>
""".format(stylesheet=url_for("static", filename="style.css"),
           tbody="\n".join(tbody))

    return html

app.run(debug=True)
