#!/usr/bin/python -O
# -*- coding: utf-8 -*-

from bottle import Bottle, run, request

from model import Repository

app = Bottle()


def f_fund(fund, digits=2):
    """ decrate the fund, if positive, use green; negative, use red
    """
    if fund is None:
        return ""

    if fund > 0:
        return "<font color=green>{0:.{1}f}</font>".format(fund, digits)
    elif fund < 0:
        return "<font color=red>{0:.{1}f}</font>".format(fund, digits)
    else:
        return "{0:.{1}f}".format(fund, digits)


@app.route("/")
def hello():
    return "Hello"


@app.route("/stock_fund")
def stock_fund():
    limit = request.query.limit or '30'
    repository = Repository()

    h_tables = []
    for code,name in repository.get_codes():
        # table header
        tlines = [u"""<tr bgcolor="#a0a0a0">
    <th nowrap>{0} {1}</th>
    <th nowrap>Date</th>
    <th nowrap>Fund In</th>
    <th nowrap>Fund Out</th>
    <th nowrap>Fund Net</th>
    <th nowrap>Total %</th>
    <th nowrap>Current %</th>
    <th nowrap>Increase %</th>
</tr>""".format(code, name)]

        total_funds = 0
        total_percent = 0
        total_increase = 0

        rows = repository.get_stockdata(code, limit)

        first_row = True
        for row in rows:
            tlines.append(u"""<tr bgcolor="#eeeeee">
    {rowheader}
    <td>{date}</td>
    <td align="right">{fund_in:.1f}</td>
    <td align="right">{fund_out:.1f}</td>
    <td align="right">{fund_net}</td>
    <td align="right" nowrap><b>{percent}</b> %</td>
    <td align="right" nowrap><b>{fund_per}</b> %</td>
    <td align="right"><b>{inc_p}</b> %</td>
</tr>""".format(rowheader="<td rowspan=%d>&nbsp;</td>" % (len(rows))
                if first_row else "",
                date=row.date,
                fund_in=row.fund_in,
                fund_out=row.fund_out,
                fund_net=f_fund(row.fund_net),
                percent=f_fund(row.percent, 3),
                fund_per=f_fund(row.fund_per),
                inc_p=f_fund(row.inc_p),
                ))
            total_funds += row.fund_net
            total_percent += row.percent
            total_increase += row.inc_p

            first_row = False

        # table footer
        tlines.append("""<tr bgcolor="#eeeeee">
    <td></td>
    <td align="center">Total</td>
    <td></td>
    <td></td>
    <td align="right">{0}</td>
    <td align="right"><b>{1}</b> %</td>
    <td></td>
    <td align="right"><b>{2}</b> %</td>
</tr>""".format(f_fund(total_funds),
                f_fund(total_percent, 3),
                f_fund(total_increase), ))

        h_tables.append(u"""<br/>
<table border=0 cellspacing="1" cellpadding="5">
<col width="70">
<col width="100">
<col width="70">
<col width="80">
<col width="80">
<col width="70">
<col width="80">
<col width="90">
{tbody}
</table>
<br/>""".format(tbody="\n".join(tlines)))

    html = u"""<html>
<title>Stock Funds</title>
<style type="text/css">
body {{
    font-family: Aria, Helvetica;
}}
</style>
<body>
{0}
</body>
</html>
""".format("\n".join(h_tables))

    return html


run(app, host="localhost", port=8088, debug=True)
